### ISSUE TITLE
display: flex bug -> flexbox bug, not css issue.

### ISSUE THREAD

**Issue by morfyum** [morfyum/maincss#2]
Currently webkit based browsers show wrong my dropdown menu, because I fix a flexbox bug on Chrome/Firefox.

Dropdown menu (`.header-flex-element`) with `display: block` property works as excepted...

`.header-flex-dropdown`  -> This element has extra `margin: 26px, 0, 0, 0` because flexbox ignore text content inside the flex elements. `<- BUG in blink/spidermonkey?`
This element is a `display: none` element, and get a .show poroperty (add `display: flex`) for show content.

```css
.header-flex-element {
  display: flex; 
}

.show {
  display: flex;
}

.header-flex-dropdown {
  display: none;
  margin: 26px 0 0 0; 
}
```

`.header-flex-element`  -> This is an flex element (`display: flex`), because my css based on flexbox and all element flexbox element.
By default, flexbox ignore font-size and/or text in `div` on Chrome and Firefox.

This is the problem for which required 26px `margin-top` in `.header-flex-dropdown`

On webkit browsers, show this extra 26 pixel. <- `BUG in webkit? `

When you modify `display: flex` to `display: block` 26 pixel margin no longer needed.
On a `webkit` browser `flex` work without issues, and this 26 pixel is extra space between element and showed menu.
